# Generated by Django 4.1.1 on 2022-09-22 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название заявки', max_length=20)),
                ('description', models.TextField(help_text='Описание заявки', max_length=1000)),
                ('category', models.CharField(choices=[('3d', '3D-дизайн'), ('2d', '2D-дизайн'), ('эс', 'Эскиз')], default=None, help_text='Категория заявки', max_length=2)),
                ('plan', models.ImageField(upload_to='uploads/% Y/% m/% d/')),
                ('date', models.DateField(auto_now=True)),
                ('status', models.CharField(choices=[('н', 'Новая'), ('п', 'Принято в работу'), ('в', 'Выполнено')], default='н', help_text='Статус заявки', max_length=1)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
