# Generated by Django 4.1.1 on 2022-09-24 01:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название заявки', max_length=20)),
                ('description', models.TextField(help_text='Описание заявки', max_length=1000)),
                ('plan', models.ImageField(upload_to='app/files/plans')),
                ('date', models.DateField(auto_now=True)),
                ('status', models.CharField(choices=[('н', 'Новая'), ('п', 'Принято в работу'), ('в', 'Выполнено')], default='н', help_text='Статус заявки', max_length=1)),
                ('design', models.ImageField(blank=True, upload_to='app/files/designs')),
                ('orderer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
