# Generated by Django 4.1.1 on 2022-09-24 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите категорию заявки', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='category',
            field=models.ManyToManyField(help_text='Категория заявки', to='app.category'),
        ),
    ]
