# Generated by Django 4.1.1 on 2022-09-29 07:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_order_comment_alter_order_orderer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='plan',
            field=models.ImageField(upload_to='app/files/plans', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'bmp'])]),
        ),
    ]
